config/routes.rb
SampleApp::Application.routes.draw do
  
  get "pages/help"
  get "pages/home"
  get "pages/about"
  get "pages/contact"

  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  
  root :to => 'pages#home'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end

  def contact
    @title = "Contact"
  end
  
  def about
    @title = "About"
  end
  
  def help
    @title = "Help"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_stylesheets.html.haml
= stylesheet_link_tag 'blueprint/screen', :media => 'screen'
= stylesheet_link_tag 'blueprint/print', :media => 'print'
=raw "<!--[if lt IE 8]>#{stylesheet_link_tag 'blueprint/ie'}<![endif]-->"
<!--[if lt IE 9]><script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
= stylesheet_link_tag	"application", :media => "all"

app/views/layouts/application.html.haml
!!! html
%html
	%head
		%title= "Ruby on Rails Sample App | #{@title}"
		= javascript_include_tag "application"
		= render "layouts/stylesheets"
		= csrf_meta_tags
	%body
		%div.container

			-# Header
			%header 
				- logo = image_tag("rails.png", :alt=>'Sample App', :class=>'round')
				= link_to logo, root_path
				%nav.round
					%ul
						%li= link_to 'Home', root_path
						%li= link_to 'About', about_path
						%li= link_to 'Help', help_path	
						%li= link_to 'Sign in', '#'

			-# Main Section
			%section.round
				= yield

			-# Footer
			%footer
				%nav.round
					%ul
						%li= link_to "About","#"
						%li= link_to "Contact", "#"
						%li
							%a= link_to "News","http://www.adrianmejiarosario.com/"

app/views/pages/about.html.haml
%h1 About
%p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec eget est arcu, sed volutpat lorem. Praesent id mauris enim. Curabitur ullamcorper pulvinar neque sed semper. Phasellus ultricies orci non diam ultricies elementum. Nam consectetur ornare urna, sagittis mattis lacus mollis sit amet. Aliquam erat volutpat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut sit amet felis et eros hendrerit faucibus. Sed tellus leo, pulvinar sit amet ultricies vitae, aliquam in tellus. Sed a dolor elit, ac mollis turpis. Quisque et velit est, eu convallis nulla. Lorem ipsum dolor sit amet, consectetur adipiscing elit.

%p Praesent viverra eros non risus imperdiet eleifend molestie orci posuere. Donec pulvinar venenatis suscipit. Praesent malesuada ipsum ut urna feugiat dignissim. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Maecenas id purus a mi rhoncus hendrerit. Quisque sit amet dictum sem. Phasellus faucibus nulla vitae urna hendrerit a euismod ipsum dignissim. Sed mauris sapien, scelerisque sed pulvinar id, egestas auctor ante. Integer egestas ornare felis ac malesuada. Sed risus massa, hendrerit sit amet bibendum at, imperdiet vel est. Morbi lectus turpis, consequat id varius nec, aliquet vel urna. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec blandit dolor in justo eleifend imperdiet. Proin ullamcorper, tellus nec tincidunt luctus, purus dolor luctus justo, dictum porta quam neque id ligula. Vivamus viverra, libero eget dictum egestas, turpis elit aliquam nisi, non dignissim est nibh id lacus.

app/views/pages/contact.html.haml
%h1 Pages#contact
%p Find me in app/views/pages/contact.html.haml

app/views/pages/help.html.haml
%h1 Pages#help
%p Find me in app/views/pages/help.html.haml

app/views/pages/home.html.haml
%h1 Home

= link_to 'Sign up',"#", :class=>"signup_button round"

%p Pellentesque semper nibh in erat consectetur interdum. Vestibulum molestie quam ac urna pretium quis feugiat turpis aliquet. Nullam volutpat sapien ut mi eleifend eu cursus lectus accumsan. In sit amet elit ut leo facilisis viverra. Vestibulum sollicitudin augue ut ante vulputate non vehicula diam imperdiet. Quisque eu lacus quam. Nunc quis lorem sem, sit amet mollis purus. Ut vel nisi sapien, vel vestibulum urna. Vivamus tristique erat ac purus vulputate vehicula. Etiam varius mi in dolor facilisis id ultrices felis pretium. Etiam non nulla condimentum enim cursus blandit sit amet et sapien. Donec fermentum, neque sed eleifend accumsan, leo felis aliquam lorem, non imperdiet justo nisi vel sem. Ut ut venenatis tortor. Cras sollicitudin ornare euismod. 